[project]
name = "quantkit"
version = "0.1.0"
requires-python = ">=3.10"
dependencies = [
  "typer>=0.12",
  "pydantic>=2",
  "python-dotenv>=1",
  "pandas>=2",
  "numpy>=1.26",
  "matplotlib>=3.8",
]

[project.scripts]
quant = "quantkit.cli:app"

