[tool.ruff]
target-version = "py311"
line-length = 100
src = ["src/quantkit/data", "src/quantkit/cli_data.py"]
ignore = ["E401","E701","E702","E741","F401","F811","F841"]

[tool.mypy]
ignore_errors = true
