name: breadth_intraday_snapshot

on:
  workflow_dispatch:
  schedule:
    - cron: "*/5 * * * 1-5"

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      TZ: Europe/Stockholm
      PYTHONPATH: ${{ github.workspace }}/src
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: "pip"
          cache-dependency-path: requirements.txt

      - name: Install deps + package (editable)
        run: |
          python -m pip install -U pip
          pip install -r requirements.txt
          pip install -e .

      - name: Verify import path
        run: |
          python - <<'PY'
          import sys, importlib.util
          print("sys.path[0]:", sys.path[0])
          print("quantkit importable?", importlib.util.find_spec("quantkit") is not None)
          PY

      - name: Compute OUT_PREFIX
        shell: bash
        run: |
          if [[ -n "${{ secrets.S3_PREFIX }}" ]]; then
            OUT_PREFIX="${{ secrets.S3_PREFIX }}"
          elif [[ -n "${{ vars.S3_PREFIX }}" ]]; then
            OUT_PREFIX="${{ vars.S3_PREFIX }}"
          else
            OUT_PREFIX="storage"
          fi
          echo "OUT_PREFIX=${OUT_PREFIX}" >> $GITHUB_ENV

      - name: Build breadth (intraday)
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
        run: |
          python -m quantkit.snapshots.breadth_snapshot build \
            --out-agg "${OUT_PREFIX}/snapshots/breadth/latest.parquet" \
            --out-sym "${OUT_PREFIX}/snapshots/breadth/symbols/latest.parquet"
