name: breadth_eod_snapshot

on:
  workflow_dispatch:
  schedule:
    - cron: "5 20 * * 1-5" # ca 20:05 UTC vardagar (justera vid behov)

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install deps + package (editable)
        run: |
          python -m pip install -U pip
          pip install -r requirements.txt
          pip install -e .

      - name: Compute OUT_PREFIX
        shell: bash
        run: |
          if [[ -z "${S3_PREFIX}" && -n "${{ vars.S3_PREFIX }}" ]]; then
            export S3_PREFIX="${{ vars.S3_PREFIX }}"
          fi
          if [[ -z "${S3_PREFIX}" ]]; then
            OUT_PREFIX="storage"
          else
            OUT_PREFIX="${S3_PREFIX}"
          fi
          echo "OUT_PREFIX=${OUT_PREFIX}" >> $GITHUB_ENV

      - name: Build breadth snapshot
        env:
          PYTHONPATH: ${{ github.workspace }}/src
          S3_PREFIX: ${{ secrets.S3_PREFIX }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
        run: |
          OUT_PREFIX="${S3_PREFIX:-storage}"
          python -m quantkit.snapshots.breadth_snapshot build \
            --out-sym "${OUT_PREFIX}/snapshots/breadth/symbols/latest.parquet" \
            --out-agg "${OUT_PREFIX}/snapshots/breadth/latest.parquet"
                  
      - name: Verify import path
        env:
          PYTHONPATH: ${{ github.workspace }}/src
        run: |
          python -c "import sys, importlib.util; print('sys.path[0]:', sys.path[0]); print('quantkit importable?', importlib.util.find_spec('quantkit') is not None)"


