name: breadth_intraday_snapshot

on:
  workflow_dispatch:
  schedule:
    - cron: "*/15 * * * 1-5" # var 15:e minut på vardagar

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install deps + package (editable)
        run: |
          python -m pip install -U pip
          pip install -r requirements.txt
          pip install -e .

      - name: Compute OUT_PREFIX
        shell: bash
        run: |
          if [[ -z "${S3_PREFIX}" && -n "${{ vars.S3_PREFIX }}" ]]; then
            export S3_PREFIX="${{ vars.S3_PREFIX }}"
          fi
          if [[ -z "${S3_PREFIX}" ]]; then
            OUT_PREFIX="storage"
          else
            OUT_PREFIX="${S3_PREFIX}"
          fi
          echo "OUT_PREFIX=${OUT_PREFIX}" >> $GITHUB_ENV

      - name: Build Breadth snapshot (intraday)
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ vars.AWS_DEFAULT_REGION }}
        run: |
          python -m quantkit.snapshots.breadth_snapshot --out "${OUT_PREFIX}/snapshots/breadth/latest.parquet"
