name: data_intraday

on:
  workflow_dispatch:
  schedule:
    - cron: "*/5 * * * 1-5"   # var 5:e minut, mån-fre (UTC)

permissions:
  contents: read

jobs:
  sync:
    runs-on: ubuntu-latest
    env:
      EODHD_TOKEN: ${{ secrets.EODHD_TOKEN }}
      EODHD_API_KEY: ${{ secrets.EODHD_API_KEY }}
      ALPHA_VANTAGE_API_KEY: ${{ secrets.ALPHA_VANTAGE_API_KEY }}
      TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
      TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      PARQUET_DIR: ./storage/parquet
      DUCKDB_PATH: ./db/quant.duckdb
      TZ: Europe/Stockholm
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Install deps
        run: |
          python -m pip install -U pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          pip install -e .
      - name: Show watchlist (if any)
        run: |
          if [ -f watchlist.yaml ]; then
            echo "watchlist.yaml present"
          elif [ -f config/tickers.txt ]; then
            echo "Tickers:"; sed 's/^/ - /' config/tickers.txt
          else
            echo "::warning::No watchlist.yaml or config/tickers.txt found"
          fi
      - name: Sync intraday (5m)
        run: |
          python -m quantkit.cli_data sync \
            --interval "5m" \
            --days 10 \
            --sleep-between 0.3 \
            --gate-hours
