name: data_intraday_st

on:
  schedule:
    - cron: "*/5 * * * 1-5"
  workflow_dispatch: {}

jobs:
  intraday:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install deps
        run: |
          python -m pip install -U pip
          pip install -r requirements.txt
          pip install -e .
          pip install awscli

      - name: Build ST ticker list
        id: build_list
        run: |
          echo "tickers=$(python .github/scripts/build_tickers.py ST)" >> "$GITHUB_OUTPUT"
          python .github/scripts/build_tickers.py ST

      - name: Sync intraday ST (EOD+5m)
        env:
          EODHD_API_KEY: ${{ secrets.EODHD_API_KEY }}
        run: |
          python -m quantkit.cli_data --interval "EOD,5m" --intra-days 10 \
            --tickers "${{ steps.build_list.outputs.tickers }}"

      - name: Push to S3
        env:
          AWS_ACCESS_KEY_ID:     ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION:            ${{ secrets.AWS_REGION }}
          S3_BUCKET:             ${{ secrets.S3_BUCKET }}
        run: |
          aws s3 sync storage "s3://${S3_BUCKET}" --delete
