name: data_eod

on:
  schedule:
    - cron: "30 21 * * 1-5" # 21:30 UTC vardagar (efter US stängt)
  workflow_dispatch:

jobs:
  eod:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Installera
        run: |
          python -m pip install -U pip
          pip install -e . awscli
      - name: Kör EOD för alla i watchlist
        env:
          EODHD_API_KEY: ${{ secrets.EODHD_API_KEY }}
        run: |
          python - <<'PY'
          import yaml,subprocess,shlex
          doc=yaml.safe_load(open('watchlist.yaml','r',encoding='utf-8')) or {}
          items=doc.get('items',[]) or doc.get('tickers',[])
          def code(x): return x if isinstance(x,str) else (x or {}).get('code')
          syms=[code(i) for i in items if code(i)]
          if syms:
              cmd=f"python -m quantkit.cli_data --interval EOD --tickers {','.join(syms)}"
              print(cmd)
              subprocess.check_call(shlex.split(cmd))
          PY
      - name: Sync till S3
        env:
          AWS_ACCESS_KEY_ID:     ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION:            ${{ secrets.AWS_REGION }}
          S3_BUCKET:             ${{ secrets.S3_BUCKET }}
        run: |
          aws s3 sync storage "s3://${S3_BUCKET}" --delete
