name: data_eod

on:
  schedule:
    - cron: "5 20 * * 1-5"  # ca efter US close (justera vid behov)
    - cron: "5 16 * * 1-5"  # ca efter Stockholm close
  workflow_dispatch: {}

jobs:
  eod:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: "3.12" }
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -e .
          pip install awscli
      - name: Sync EOD for all
        env:
          EODHD_API_KEY: ${{ secrets.EODHD_API_KEY }}
        run: |
          python -m quantkit.cli_data --interval "EOD" --eod-days 9000
      - name: Push to S3
        env:
          AWS_ACCESS_KEY_ID:     ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION:            ${{ secrets.AWS_REGION }}
          S3_BUCKET:             ${{ secrets.S3_BUCKET }}
        run: |
          aws s3 sync storage "s3://${S3_BUCKET}" --delete
