name: Intraday US (5m)
on:
  schedule:
    - cron: "*/10 15-22 * * 1-5"   # var 10:e minut 09:00–17:00 CET/CEST ungefär
  workflow_dispatch: {}
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - run: pip install -r requirements.txt
      - run: cp .env.example .env
      - run: echo "EODHD_API_KEY=${{ secrets.EODHD_API_KEY }}" >> .env
      - run: python -m src.quantkit.cli ingest --symbol AAPL.US --timeframe 5m
      - run: python -m src.quantkit.cli alerts --timeframe 5m
