name: data_intraday_us_1m

on:
  workflow_dispatch:
  schedule:
    - cron: "* 13-21 * * 1-5"   # varje minut runt US-session (gate nedan styr exakt)

concurrency:
  group: ingest-us-1m-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ingest:
    runs-on: ubuntu-latest
    env:
      TZ: Europe/Stockholm
      PYTHONPATH: ${{ github.workspace }}/src
      EODHD_API_KEY: ${{ secrets.EODHD_API_KEY }}
      EODHD_API_TOKEN: ${{ secrets.EODHD_API_KEY }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: "pip"
          cache-dependency-path: requirements.txt

      - name: Install deps + package
        run: |
          python -m pip install -U pip
          pip install -r requirements.txt
          pip install -e .

      - name: Gate (US open 15:30–22:05)
        id: gate
        shell: bash
        run: |
          NOW=$(TZ=Europe/Stockholm date +%H%M)
          DOW=$(TZ=Europe/Stockholm date +%u)
          open=false
          if [ "$DOW" -le 5 ]; then
            if [ "$NOW" -ge 1530 ] && [ "$NOW" -le 2205 ]; then open=true; fi
          fi
          echo "open=$open" >> "$GITHUB_OUTPUT"

      - name: Run intraday ingest (US 1m)
        if: steps.gate.outputs.open == 'true'
        run: |
          python -m quantkit data-intraday --timeframe 1m --tickers-file config/tickers_intraday_us.txt --force

