name: data_eod

on:
  workflow_dispatch:
  schedule:
    - cron: "15 21 * * 1-5"   # ca efter US close (21:15 UTC), mån-fre

permissions:
  contents: read

jobs:
  sync:
    runs-on: ubuntu-latest
    env:
      EODHD_TOKEN: ${{ secrets.EODHD_TOKEN }}
      EODHD_API_KEY: ${{ secrets.EODHD_API_KEY }}
      ALPHA_VANTAGE_API_KEY: ${{ secrets.ALPHA_VANTAGE_API_KEY }}
      PARQUET_DIR: ./storage/parquet
      DUCKDB_PATH: ./db/quant.duckdb
      TZ: Europe/Stockholm
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Install deps
        run: |
          python -m pip install -U pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          pip install -e .
      - name: Sync EOD
        run: |
          python -m quantkit.cli_data sync \
            --interval "EOD" \
            --eod-days 9000 \
            --sleep-between 0.1 \
            --no-gate-hours
