name: live

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  live:
    runs-on: ubuntu-latest

    env:
      EODHD_TOKEN: ${{ secrets.EODHD_TOKEN }}
      ALPHA_VANTAGE_API_KEY: ${{ secrets.ALPHA_VANTAGE_API_KEY }}
      TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
      TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      PARQUET_DIR: ./storage/parquet
      DUCKDB_PATH: ./db/quant.duckdb
      TZ: Europe/Stockholm

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install deps
        run: |
          python -m pip install -U pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Preflight (PowerShell)
        shell: pwsh
        run: ./scripts/Check-QuantEnv.ps1 -Mode CI -WriteEnvFile

      - name: Run live process
        shell: bash
        run: |
          if [ -f live.py ]; then
            python live.py
          elif python -c "import importlib.util, sys; sys.exit(0 if importlib.util.find_spec('quantkit') else 1)"; then
            python -m quantkit.live
          else
            echo "::warning::Hittade inget live-entrypoint. Lägg till live.py eller modulen quantkit.live."
          fi

          