name: Live Alerts

on:
  workflow_dispatch:
    inputs:
      symbols:
        description: 'Comma-separated Yahoo tickers (ex: ABB.ST,ERIC-B.ST)'
        required: true
        default: 'ABB.ST,ERIC-B.ST'
      minutes_fetch:
        description: 'How many minutes of 1m data to fetch (Yahoo 1m ≲ 7d)'
        required: true
        default: '1950'
      use_optuna_best:
        description: 'Use reports/<sym>_optuna_best.json'
        required: true
        default: 'true'
  schedule:
    # Kör var 5:e minut på vardagar (UTC).
    - cron: "*/5 7-16 * * 1-5"

permissions:
  contents: read

concurrency:
  group: live-alerts
  cancel-in-progress: true

jobs:
  run:
    runs-on: ubuntu-latest
    env:
      SYMBOLS: ${{ github.event.inputs.symbols || 'ABB.ST,ERIC-B.ST' }}
      MINUTES_FETCH: ${{ github.event.inputs.minutes_fetch || '1950' }}
      USE_OPTUNA_BEST: ${{ github.event.inputs.use_optuna_best || 'true' }}
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
      TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
      ALERT_WEBHOOK_URL: ${{ secrets.ALERT_WEBHOOK_URL }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install -U pip
          if [ -f requirements.txt ]; then
            pip install -r requirements.txt
          else
            pip install duckdb requests yfinance pandas numpy
          fi

      - name: Ensure folders
        run: |
          mkdir -p db state reports pages

      - name: Run live alerts
        shell: bash
        run: |
          python -m scripts.live_alerts \
            --symbols "${SYMBOLS}" \
            --source yahoo \
            $([ "${USE_OPTUNA_BEST}" = "true" ] && echo --use_optuna_best) \
            --minutes_fetch "${MINUTES_FETCH}" \
            --slack_webhook "${SLACK_WEBHOOK_URL}" \
            --tg_token "${TELEGRAM_BOT_TOKEN}" \
            --tg_chat "${TELEGRAM_CHAT_ID}" \
            --webhook "${ALERT_WEBHOOK_URL}"

            