name: nightly_ingest

on:
  schedule:
    - cron: "15 1 * * *"
  workflow_dispatch:

permissions:
  contents: read

jobs:
  ingest:
    runs-on: ubuntu-latest
    env:
      EODHD_TOKEN: ${{ secrets.EODHD_TOKEN }}
      ALPHA_VANTAGE_API_KEY: ${{ secrets.ALPHA_VANTAGE_API_KEY }}
      TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
      TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      PARQUET_DIR: ./storage/parquet
      DUCKDB_PATH: ./db/quant.duckdb
      TZ: Europe/Stockholm
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install deps
        run: |
          python -m pip install -U pip
          pip install -r requirements.txt

      - name: Preflight (pwsh)
        shell: pwsh
        run: |
          ./scripts/Check-QuantEnv.ps1 -Mode CI -WriteEnvFile

      - name: Run ingest
        run: |
          set -e
          if [ -f "fundamentals_ingest.py" ]; then
            python fundamentals_ingest.py | tee nightly.log
          else
            python - <<'PY' | tee nightly.log
import importlib.util, sys
spec = importlib.util.find_spec("quantkit.ingest")
if spec:
    import importlib
    m = importlib.import_module("quantkit.ingest")
    if hasattr(m, "main"):
        sys.exit(m.main() or 0)
    else:
        print("quantkit.ingest found but no main(); doing nothing.")
        sys.exit(0)
else:
    print("No ingest entrypoint found.")
    sys.exit(1)
PY
          fi

      - name: Upload log
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: nightly-log
          path: nightly.log
