name: Snapshots (Hotlists + Signals + Movers)

on:
  schedule:
    # kör vardagar var 5:e minut 07–17 CET och 15–22 CET (anpassa själv)
    - cron: "*/5 6-17 * * 1-5"
    - cron: "*/5 14-22 * * 1-5"
  workflow_dispatch: {}

jobs:
  run:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install deps (editable)
        run: |
          python -m pip install -U pip
          pip install -r requirements.txt
          pip install -e .
        env:
          PIP_DISABLE_PIP_VERSION_CHECK: "1"

      - name: Env
        run: |
          echo "EODHD_API_KEY=${{ secrets.EODHD_API_KEY }}" >> $GITHUB_ENV
          echo "PYTHONPATH=$GITHUB_WORKSPACE/src" >> $GITHUB_ENV

      - name: Hotlists
        run: python -m quantkit snapshot-hotlists --timeframe 5m --force

      - name: Signals
        run: python -m quantkit snapshot-signals --force

      - name: Movers
        run: python -m quantkit snapshot-movers --force

      # (valfritt) sync till S3 – sätt upp secrets: AWS_* och S3_PREFIX
      - name: Upload to S3
        if: env.S3_PREFIX != ''
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
          S3_PREFIX: ${{ secrets.S3_PREFIX }}
        run: |
          python - << 'PY'
          import os, boto3, pathlib
          s3 = boto3.client("s3", region_name=os.environ["AWS_REGION"])
          bkt, *key = os.environ["S3_PREFIX"].replace("s3://","").split("/",1)
          key = (key[0] if key else "").rstrip("/")
          for p in pathlib.Path("storage/snapshots").rglob("*.parquet"):
              k = f"{key}/{p.as_posix().split('storage/snapshots/',1)[1]}"
              print("upload", p, "→", f"s3://{bkt}/{k}")
              s3.upload_file(str(p), bkt, k)
          PY
